version: "1.0"
scanner:
  # global setting
  global:
    default_arches:
      - linux/amd64
      - linux/arm64
    # support format: 24h, 1d, 1w, 30m
    default_interval: "1d"
    output:
      repo: https://github.com/Ascend/cann-container-image
      path: security/reports

# specific image scan
images:
  # use global scan cycle
  - image: "cann"
    tags:
      - tag: "quay.io/ascend/cann:8.3.rc1.alpha003-910b-ubuntu22.04-py3.11"
      - tag: "quay.io/ascend/cann:8.3.rc1.alpha003-910b-openeuler24.03-py3.11"
      - tag: "quay.io/ascend/cann:8.2.rc2-910b-ubuntu22.04-py3.11"
      - tag: "quay.io/ascend/cann:8.2.rc2-910b-openeuler24.03-py3.11"
      - tag: "quay.io/ascend/cann:8.2.rc1-910b-ubuntu22.04-py3.11"
      - tag: "quay.io/ascend/cann:8.2.rc1-910b-openeuler24.03-py3.11"

# notice setting (option)
notifications:
  email:
    enabled: true
    recipients:
      - "security@example.com"
    smtp_server: "smtp.example.com:587"

  slack:
    enabled: false
    webhook_url: ""